name: CD

on: push

jobs:
  publish:
    name: Deploying ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [macos, linux32, linux64]
        include:
          - build_target: macos
            os: macos-latest
            artifact_suffix: macos-x86_64
            target_os: darwin
            target_arch: amd64
          - build_target: linux32
            os: ubuntu-latest
            artifact_suffix: linux-x86_32
            target_arch: 386
            target_os: linux
          - build_target: linux64
            os: ubuntu-latest
            artifact_suffix: linux-x86_64
            target_arch: amd64
            target_os: linux
    env:
      DESTDIR: ./${{ matrix.artifact_suffix }}
    steps:
      - name: Set up access
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: Set up Linux deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update
      - name: Set up Linux32 deps
        if: matrix.target_arch == '386'
        run: sudo apt update
      - name: Build
        run: GOOS=${{ matrix.target_os }} GOARCH=${{ matrix.target_arch }} make
      - name: Install
        run: make install
      - name: Package
        shell: bash
        run: tar czvf trt-${{ matrix.artifact_suffix }}.tar.gz ${{ matrix.artifact_suffix }}/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: trt-${{ matrix.artifact_suffix }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
